from django.db import models

# Model representing an advertisement
class Ad(models.Model):
    title = models.CharField(max_length=255) # Title of the advertisement
    content = models.TextField() # Description or content of the ad
    is_active = models.BooleanField(default=True) # Whether the ad is active
    revenue = models.DecimalField(max_digits=10, decimal_places=2) # Revenue generated by the ad

    def __str__(self):
        return self.title # String representation of the ad
